language: julia

os:
  - windows
  - linux
  - osx

julia:
  - 1
  - 1.3
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("OceanographyCruises")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';

